version: "3.9"

services:
    backup:
        build:
            context: ./src
        restart: unless-stopped
        working_dir: /app
        environment:
            - EETLIJST_USERNAME
            - EETLIJST_PASSWORD
        volumes:
            - ./backups:/app/backups
